version: '3'
services:
  homeassistant:
    user: "1000:1000"
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config:z
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant.rule=Host(`home.gandro.dev`)"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
networks:
  default:
    external: true
    name: traefik_services
