version: "3"

services:
  router:
    image: traefik:v2.10
    restart: always
    privileged: true # docker socket access
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./acme:/etc/traefik/acme:z
      - ./conf.d:/etc/traefik/conf.d:z
      - ./htpasswd:/etc/traefik/htpasswd:ro,z
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro,z
      - /var/run/docker.sock:/var/run/docker.sock:ro,z
    extra_hosts:
        - host.docker.internal:172.17.0.1
  static:
    image: "nginx"
    volumes:
      - ./html:/usr/share/nginx/html:ro,z
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static.rule=Host(`gandro.dev`)"
networks:
  default:
    external: false
    name: traefik_services
