version: '3'

services:
  thelounge:
    image: ghcr.io/thelounge/thelounge:latest
    expose:
      - "9000"
    volumes:
      - ./config:/var/opt/thelounge:z
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.thelounge.rule=Host(`irc.gandro.dev`)"
      - "traefik.http.services.thelounge.loadbalancer.server.port=9000"
networks:
  default:
    external: true
    name: traefik_services
